# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import redesocial_pb2 as redesocial__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in redesocial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RedeSocialStub(object):
    """Serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Postar = channel.unary_unary(
                '/redesocial.RedeSocial/Postar',
                request_serializer=redesocial__pb2.Postagem.SerializeToString,
                response_deserializer=redesocial__pb2.Ack.FromString,
                _registered_method=True)
        self.Seguir = channel.unary_unary(
                '/redesocial.RedeSocial/Seguir',
                request_serializer=redesocial__pb2.SeguirRequest.SerializeToString,
                response_deserializer=redesocial__pb2.Ack.FromString,
                _registered_method=True)
        self.EnviarMensagem = channel.unary_unary(
                '/redesocial.RedeSocial/EnviarMensagem',
                request_serializer=redesocial__pb2.Mensagem.SerializeToString,
                response_deserializer=redesocial__pb2.Ack.FromString,
                _registered_method=True)
        self.SincronizarRelogio = channel.unary_unary(
                '/redesocial.RedeSocial/SincronizarRelogio',
                request_serializer=redesocial__pb2.ClockRequest.SerializeToString,
                response_deserializer=redesocial__pb2.ClockReply.FromString,
                _registered_method=True)


class RedeSocialServicer(object):
    """Serviço
    """

    def Postar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seguir(self, request, context):
        """<<< ALTERADO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SincronizarRelogio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedeSocialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Postar': grpc.unary_unary_rpc_method_handler(
                    servicer.Postar,
                    request_deserializer=redesocial__pb2.Postagem.FromString,
                    response_serializer=redesocial__pb2.Ack.SerializeToString,
            ),
            'Seguir': grpc.unary_unary_rpc_method_handler(
                    servicer.Seguir,
                    request_deserializer=redesocial__pb2.SeguirRequest.FromString,
                    response_serializer=redesocial__pb2.Ack.SerializeToString,
            ),
            'EnviarMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensagem,
                    request_deserializer=redesocial__pb2.Mensagem.FromString,
                    response_serializer=redesocial__pb2.Ack.SerializeToString,
            ),
            'SincronizarRelogio': grpc.unary_unary_rpc_method_handler(
                    servicer.SincronizarRelogio,
                    request_deserializer=redesocial__pb2.ClockRequest.FromString,
                    response_serializer=redesocial__pb2.ClockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'redesocial.RedeSocial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('redesocial.RedeSocial', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RedeSocial(object):
    """Serviço
    """

    @staticmethod
    def Postar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redesocial.RedeSocial/Postar',
            redesocial__pb2.Postagem.SerializeToString,
            redesocial__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seguir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redesocial.RedeSocial/Seguir',
            redesocial__pb2.SeguirRequest.SerializeToString,
            redesocial__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redesocial.RedeSocial/EnviarMensagem',
            redesocial__pb2.Mensagem.SerializeToString,
            redesocial__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SincronizarRelogio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/redesocial.RedeSocial/SincronizarRelogio',
            redesocial__pb2.ClockRequest.SerializeToString,
            redesocial__pb2.ClockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
