# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: redesocial.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'redesocial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10redesocial.proto\x12\nredesocial\"&\n\x0c\x43lockRequest\x12\x16\n\x0erelogio_fisico\x18\x01 \x01(\x01\"\x1c\n\nClockReply\x12\x0e\n\x06offset\x18\x01 \x01(\x01\"a\n\x08Postagem\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\t\x12\x18\n\x10timestamp_logico\x18\x03 \x01(\x01\x12\x18\n\x10timestamp_fisico\x18\x04 \x01(\x01\"Q\n\x08Mensagem\x12\r\n\x05\x66rom_\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\x12\x18\n\x10timestamp_logico\x18\x04 \x01(\x01\"6\n\rSeguirRequest\x12\x12\n\nseguidorid\x18\x01 \x01(\t\x12\x11\n\tseguidoid\x18\x02 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf4\x01\n\nRedeSocial\x12/\n\x06Postar\x12\x14.redesocial.Postagem\x1a\x0f.redesocial.Ack\x12\x34\n\x06Seguir\x12\x19.redesocial.SeguirRequest\x1a\x0f.redesocial.Ack\x12\x37\n\x0e\x45nviarMensagem\x12\x14.redesocial.Mensagem\x1a\x0f.redesocial.Ack\x12\x46\n\x12SincronizarRelogio\x12\x18.redesocial.ClockRequest\x1a\x16.redesocial.ClockReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'redesocial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKREQUEST']._serialized_start=32
  _globals['_CLOCKREQUEST']._serialized_end=70
  _globals['_CLOCKREPLY']._serialized_start=72
  _globals['_CLOCKREPLY']._serialized_end=100
  _globals['_POSTAGEM']._serialized_start=102
  _globals['_POSTAGEM']._serialized_end=199
  _globals['_MENSAGEM']._serialized_start=201
  _globals['_MENSAGEM']._serialized_end=282
  _globals['_SEGUIRREQUEST']._serialized_start=284
  _globals['_SEGUIRREQUEST']._serialized_end=338
  _globals['_ACK']._serialized_start=340
  _globals['_ACK']._serialized_end=362
  _globals['_REDESOCIAL']._serialized_start=365
  _globals['_REDESOCIAL']._serialized_end=609
# @@protoc_insertion_point(module_scope)
