// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: redesocial.proto

package clientes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagens para sincronização de relógio
type ClockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelogioFisico float64                `protobuf:"fixed64,1,opt,name=relogio_fisico,json=relogioFisico,proto3" json:"relogio_fisico,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockRequest) Reset() {
	*x = ClockRequest{}
	mi := &file_redesocial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockRequest) ProtoMessage() {}

func (x *ClockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockRequest.ProtoReflect.Descriptor instead.
func (*ClockRequest) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{0}
}

func (x *ClockRequest) GetRelogioFisico() float64 {
	if x != nil {
		return x.RelogioFisico
	}
	return 0
}

type ClockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        float64                `protobuf:"fixed64,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockReply) Reset() {
	*x = ClockReply{}
	mi := &file_redesocial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockReply) ProtoMessage() {}

func (x *ClockReply) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockReply.ProtoReflect.Descriptor instead.
func (*ClockReply) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{1}
}

func (x *ClockReply) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Mensagens principais
type Postagem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Conteudo        string                 `protobuf:"bytes,2,opt,name=conteudo,proto3" json:"conteudo,omitempty"`
	TimestampLogico float64                `protobuf:"fixed64,3,opt,name=timestamp_logico,json=timestampLogico,proto3" json:"timestamp_logico,omitempty"`
	TimestampFisico float64                `protobuf:"fixed64,4,opt,name=timestamp_fisico,json=timestampFisico,proto3" json:"timestamp_fisico,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Postagem) Reset() {
	*x = Postagem{}
	mi := &file_redesocial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Postagem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Postagem) ProtoMessage() {}

func (x *Postagem) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Postagem.ProtoReflect.Descriptor instead.
func (*Postagem) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{2}
}

func (x *Postagem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Postagem) GetConteudo() string {
	if x != nil {
		return x.Conteudo
	}
	return ""
}

func (x *Postagem) GetTimestampLogico() float64 {
	if x != nil {
		return x.TimestampLogico
	}
	return 0
}

func (x *Postagem) GetTimestampFisico() float64 {
	if x != nil {
		return x.TimestampFisico
	}
	return 0
}

type Mensagem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	From_           string                 `protobuf:"bytes,1,opt,name=from_,json=from,proto3" json:"from_,omitempty"`
	To              string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Conteudo        string                 `protobuf:"bytes,3,opt,name=conteudo,proto3" json:"conteudo,omitempty"`
	TimestampLogico float64                `protobuf:"fixed64,4,opt,name=timestamp_logico,json=timestampLogico,proto3" json:"timestamp_logico,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Mensagem) Reset() {
	*x = Mensagem{}
	mi := &file_redesocial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mensagem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensagem) ProtoMessage() {}

func (x *Mensagem) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensagem.ProtoReflect.Descriptor instead.
func (*Mensagem) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{3}
}

func (x *Mensagem) GetFrom_() string {
	if x != nil {
		return x.From_
	}
	return ""
}

func (x *Mensagem) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Mensagem) GetConteudo() string {
	if x != nil {
		return x.Conteudo
	}
	return ""
}

func (x *Mensagem) GetTimestampLogico() float64 {
	if x != nil {
		return x.TimestampLogico
	}
	return 0
}

type SeguirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeguidorId    string                 `protobuf:"bytes,1,opt,name=seguidor_id,json=seguidorId,proto3" json:"seguidor_id,omitempty"`
	SeguidoId     string                 `protobuf:"bytes,2,opt,name=seguido_id,json=seguidoId,proto3" json:"seguido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeguirRequest) Reset() {
	*x = SeguirRequest{}
	mi := &file_redesocial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeguirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeguirRequest) ProtoMessage() {}

func (x *SeguirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeguirRequest.ProtoReflect.Descriptor instead.
func (*SeguirRequest) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{4}
}

func (x *SeguirRequest) GetSeguidorId() string {
	if x != nil {
		return x.SeguidorId
	}
	return ""
}

func (x *SeguirRequest) GetSeguidoId() string {
	if x != nil {
		return x.SeguidoId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_redesocial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_redesocial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_redesocial_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_redesocial_proto protoreflect.FileDescriptor

const file_redesocial_proto_rawDesc = "" +
	"\n" +
	"\x10redesocial.proto\x12\n" +
	"redesocial\"5\n" +
	"\fClockRequest\x12%\n" +
	"\x0erelogio_fisico\x18\x01 \x01(\x01R\rrelogioFisico\"$\n" +
	"\n" +
	"ClockReply\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x01R\x06offset\"\x95\x01\n" +
	"\bPostagem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bconteudo\x18\x02 \x01(\tR\bconteudo\x12)\n" +
	"\x10timestamp_logico\x18\x03 \x01(\x01R\x0ftimestampLogico\x12)\n" +
	"\x10timestamp_fisico\x18\x04 \x01(\x01R\x0ftimestampFisico\"v\n" +
	"\bMensagem\x12\x13\n" +
	"\x05from_\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1a\n" +
	"\bconteudo\x18\x03 \x01(\tR\bconteudo\x12)\n" +
	"\x10timestamp_logico\x18\x04 \x01(\x01R\x0ftimestampLogico\"O\n" +
	"\rSeguirRequest\x12\x1f\n" +
	"\vseguidor_id\x18\x01 \x01(\tR\n" +
	"seguidorId\x12\x1d\n" +
	"\n" +
	"seguido_id\x18\x02 \x01(\tR\tseguidoId\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf4\x01\n" +
	"\n" +
	"RedeSocial\x12/\n" +
	"\x06Postar\x12\x14.redesocial.Postagem\x1a\x0f.redesocial.Ack\x124\n" +
	"\x06Seguir\x12\x19.redesocial.SeguirRequest\x1a\x0f.redesocial.Ack\x127\n" +
	"\x0eEnviarMensagem\x12\x14.redesocial.Mensagem\x1a\x0f.redesocial.Ack\x12F\n" +
	"\x12SincronizarRelogio\x12\x18.redesocial.ClockRequest\x1a\x16.redesocial.ClockReplyB\x12Z\x10projeto/clientesb\x06proto3"

var (
	file_redesocial_proto_rawDescOnce sync.Once
	file_redesocial_proto_rawDescData []byte
)

func file_redesocial_proto_rawDescGZIP() []byte {
	file_redesocial_proto_rawDescOnce.Do(func() {
		file_redesocial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redesocial_proto_rawDesc), len(file_redesocial_proto_rawDesc)))
	})
	return file_redesocial_proto_rawDescData
}

var file_redesocial_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_redesocial_proto_goTypes = []any{
	(*ClockRequest)(nil),  // 0: redesocial.ClockRequest
	(*ClockReply)(nil),    // 1: redesocial.ClockReply
	(*Postagem)(nil),      // 2: redesocial.Postagem
	(*Mensagem)(nil),      // 3: redesocial.Mensagem
	(*SeguirRequest)(nil), // 4: redesocial.SeguirRequest
	(*Ack)(nil),           // 5: redesocial.Ack
}
var file_redesocial_proto_depIdxs = []int32{
	2, // 0: redesocial.RedeSocial.Postar:input_type -> redesocial.Postagem
	4, // 1: redesocial.RedeSocial.Seguir:input_type -> redesocial.SeguirRequest
	3, // 2: redesocial.RedeSocial.EnviarMensagem:input_type -> redesocial.Mensagem
	0, // 3: redesocial.RedeSocial.SincronizarRelogio:input_type -> redesocial.ClockRequest
	5, // 4: redesocial.RedeSocial.Postar:output_type -> redesocial.Ack
	5, // 5: redesocial.RedeSocial.Seguir:output_type -> redesocial.Ack
	5, // 6: redesocial.RedeSocial.EnviarMensagem:output_type -> redesocial.Ack
	1, // 7: redesocial.RedeSocial.SincronizarRelogio:output_type -> redesocial.ClockReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redesocial_proto_init() }
func file_redesocial_proto_init() {
	if File_redesocial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redesocial_proto_rawDesc), len(file_redesocial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redesocial_proto_goTypes,
		DependencyIndexes: file_redesocial_proto_depIdxs,
		MessageInfos:      file_redesocial_proto_msgTypes,
	}.Build()
	File_redesocial_proto = out.File
	file_redesocial_proto_goTypes = nil
	file_redesocial_proto_depIdxs = nil
}
